### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to S3_Uploads_Stream_Wrapper::register() must be an instance of Aws\S3\S3ClientInterface

### ISSUE THREAD

**Issue by austingray** [humanmade/S3-Uploads#198]
Hello, looking forward to using this plugin! I cloned the repo and activated it and received the following error:

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to S3_Uploads_Stream_Wrapper::register() must be an instance of Aws\S3\S3ClientInterface, instance of Aws\S3\S3Client given, called in /path/to/httpdocs/wp-content/plugins/S3-Uploads/inc/class-s3-uploads.php on line 75 and defined in /path/to/httpdocs/wp-content/plugins/S3-Uploads/inc/class-s3-uploads-stream-wrapper.php:105
Stack trace:
#0 /path/to/httpdocs/wp-content/plugins/S3-Uploads/inc/class-s3-uploads.php(75): S3_Uploads_Stream_Wrapper::register(Object(Aws\S3\S3Client))
#1 /path/to/httpdocs/wp-content/plugins/S3-Uploads/inc/class-s3-uploads.php(45): S3_Uploads->register_stream_wrapper()
#2 /path/to/httpdocs/wp-content/plugins/S3-Uploads/s3-uploads.php(45): S3_Uploads->setup()
#3 /path/to/httpdocs/wp-includes/class-wp-hook.php(298): s3_uploads_init('')
#4 /path/to/httpdocs/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) in /path/to/httpdocs/wp-content/plugins/S3-Uploads/inc/class-s3-uploads-stream-wrapper.php on line 105
```

Will start digging into the code now and see what I find.

**Comment by austingray** [comment]
Just a note, I did leave the following two values as empty strings in `wp-config.php` prior to activating:

```
define( 'S3_UPLOADS_KEY', '' );
define( 'S3_UPLOADS_SECRET', '' );
```

However I don't think that is the issue, just wanted to make a note. I did specify the bucket name and region.

**Comment by austingray** [comment]
possible dup of #197

**Comment by austingray** [comment]
Confirmed dup, fix was to install by running:

```
git clone https://github.com/humanmade/S3-Uploads.git
cd S3-Uploads && git checkout tags/v2.0.0-beta3
```
