### ISSUE TITLE
Uploading images via Woocommerce API crashes

### ISSUE THREAD

**Issue by svaldesm** [humanmade/S3-Uploads#211]
When trying to upload, I get this error:

`Fatal error: Uncaught Error: Call to undefined function wp_tempnam() in /var/www/html/wp-content/plugins/S3-Uploads/inc/class-s3-uploads.php:246 Stack trace: #0 /var/www/html/wp-content/plugins/S3-Uploads/inc/class-s3-uploads.php(232): S3_Uploads->copy_image_from_s3('s3://sensaciona...') #1 /var/www/html/wp-includes/class-wp-hook.php(288): S3_Uploads->wp_filter_read_image_metadata(Array, 's3://sensaciona...') #2 /var/www/html/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array) #3 /var/www/html/wp-admin/includes/image.php(514): apply_filters('wp_read_image_m...', Array, 's3://sensaciona...', 2, Array) #4 /var/www/html/wp-content/plugins/woocommerce/includes/wc-rest-functions.php(152): wp_read_image_metadata('s3://sensaciona...') #5 /var/www/html/wp-content/plugins/woocommerce/includes/api/class-wc-rest-products-controller.php(1068): wc_rest_set_uploaded_image_as_attachment(Array, 0) #6 /var/www/html/wp-content/plugins/woocommerce/includes/api/class-wc-rest-products-controller.php(1017): WC_REST_Products_Contr in /var/www/html/wp-content/plugins/S3-Uploads/inc/class-s3-uploads.php on line 246`

I disabled other plugins, it's definitely S3 uploads. From what I know, seems that Woocommerce is unable to parse the URL with "s3://..."

Is there a workaround over this?

Thanks!

**Comment by svaldesm** [comment]
OK, not so elegant, but with the help of Ryan Schaffner I was able to fix it.

We added the function `wp_tempnam()` at the top of `class-s3-uploads.php` but we changed the name to `wp_temp_nam_2` and also changed the name at the function on line 247. 

What doesn't make conflicts with wp_tempnam recalling it, but also makes the same functionality available for the API.

Nevetheless, I don't think this should be closed, because the issue still exists.
