### ISSUE TITLE
IAM User creation failing

### ISSUE THREAD

**Issue by BoomOnline** [humanmade/S3-Uploads#241]
Stack trace here.

Hosting on Kinsta

PHP Fatal error:  Uncaught Error: Class 'Aws\Common\Aws' not found in /www/appliancecity_625/public/wp-content/plugins/S3-Uploads/inc/class-s3-uploads-wp-cli-command.php:160
Stack trace:
#0 [internal function]: S3_Uploads_WP_CLI_Command->create_iam_user(Array, Array)
#1 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(89): call_user_func(Array, Array, Array)
#2 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#3 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(425): call_user_func(Object(Closure), Array, Array)
#4 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(353): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#5 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(376): WP_CLI\Runner->run_command(Array, Array)
#6 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(1102): WP_CLI\Runner->_run_command_and_exit()
#7 phar:///usr/local/bin/wp/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#8 phar:///usr/local/bin/wp/php/bootstrap.php( in /www/appliancecity_625/public/wp-content/plugins/S3-Uploads/inc/class-s3-uploads-wp-cli-command.php on line 160
Fatal error: Uncaught Error: Class 'Aws\Common\Aws' not found in /www/appliancecity_625/public/wp-content/plugins/S3-Uploads/inc/class-s3-uploads-wp-cli-command.php:160
Stack trace:
#0 [internal function]: S3_Uploads_WP_CLI_Command->create_iam_user(Array, Array)
#1 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(89): call_user_func(Array, Array, Array)
#2 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#3 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(425): call_user_func(Object(Closure), Array, Array)
#4 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(353): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#5 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(376): WP_CLI\Runner->run_command(Array, Array)
#6 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(1102): WP_CLI\Runner->_run_command_and_exit()
#7 phar:///usr/local/bin/wp/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#8 phar:///usr/local/bin/wp/php/bootstrap.php( in /www/appliancecity_625/public/wp-content/plugins/S3-Uploads/inc/class-s3-uploads-wp-cli-command.php on line 160

**Comment by BoomOnline** [comment]
Just realised this is a duplicate of #95, will follow that thread instead
