### ISSUE TITLE
installed "elementor plugin" and free "hello theme"

### ISSUE THREAD

**Issue by gitmko0** [humanmade/S3-Uploads#448]
getting this error. possible to fix it?

2020/10/06 09:15:23 [error] 84#84: *296 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 2 passed to S3_Uploads::add_s3_signed_params_to_attachment_image_src() must be of the type int, string given, called in /var/web/site/public_html/wp-includes/class-wp-hook.php on line 289 and defined in /var/web/site/public_html/wp-content/plugins/S3-Uploads/inc/class-s3-uploads.php:486
Stack trace:
#0 /var/web/site/public_html/wp-includes/class-wp-hook.php(289): S3_Uploads->add_s3_signed_params_to_attachment_image_src()
#1 /var/web/site/public_html/wp-includes/plugin.php(206): WP_Hook->apply_filters()
#2 /var/web/site/public_html/wp-includes/media.php(993): apply_filters()
#3 /var/web/site/public_html/wp-content/plugins/elementor/core/kits/documents/tabs/settings-site-identity.php(24): wp_get_attachment_image_src()
#4 /var/web/site/public_html/wp-content/plugins/elementor/core/kits/documents/tabs/tab-base.php(27): Elementor\Core\Kits\Documents\Tabs\Settings_Site_Identity->register_tab_controls()
#5 /var/web/site/public_html/wp-content/pl" while reading response header from upstream, client: 3.128.139.244, server: _, request: "GET /?customize_changeset_uuid=b66bf1a6-a9d3-406f-963c-58b0c

**Comment by VlasicVojislav** [comment]
Closing this as an old issue.
