### ISSUE TITLE
Fatal error using Elementor + S3 Uploads

### ISSUE THREAD

**Issue by jeremypetersen** [humanmade/S3-Uploads#506]
Hi,

I use Elementor (+ Elementor Pro) and S3 Uploads on my WordPress website. It worked fine until I updated Elementor to the latest version :
- WordPress : v5.7
- Elementor : v3.1.4
- Elementor Pro : v3.2.1

> Fatal error: Uncaught TypeError: Argument 2 passed to S3_Uploads::add_s3_signed_params_to_attachment_image_src() must be of the type int, string given, called in /srv/app/wordpress/escande/web/wp/wp-includes/class-wp-hook.php on line 294 and defined in /srv/app/wordpress/escande/web/app/plugins/s3-uploads/inc/class-s3-uploads.php:486 Stack trace: #0 /srv/app/wordpress/escande/web/wp/wp-includes/class-wp-hook.php(294): S3_Uploads->add_s3_signed_params_to_attachment_image_src() #1 /srv/app/wordpress/escande/web/wp/wp-includes/plugin.php(212): WP_Hook->apply_filters() #2 /srv/app/wordpress/escande/web/wp/wp-includes/media.php(991): apply_filters() #3 /srv/app/wordpress/escande/web/app/plugins/elementor/core/kits/documents/tabs/settings-site-identity.php(37): wp_get_attachment_image_src() #4 /srv/app/wordpress/escande/web/app/plugins/elementor/core/kits/documents/tabs/tab-base.php(43): Elementor\Core\Kits\Documents\Tabs\Settings_Site_Identity->register_tab_controls() #5 /srv/app/wordpress/escande/web/app/plugins/elementor/cor in /srv/app/wordpress/escande/web/app/plugins/s3-uploads/inc/class-s3-uploads.php on line 486

Can you please help ?

Thanks in advance !

**Comment by VlasicVojislav** [comment]
Closing this as an old issue.
