### ISSUE TITLE
Fatal errors when using S3_UPLOADS_USE_LOCAL=true

### ISSUE THREAD

**Issue by scraddle** [humanmade/S3-Uploads#532]
Hi,

I tried to use the offline development feature S3_UPLOADS_USE_LOCAL.
Sadly when defining S3_UPLOADS_USE_LOCAL=true I get fatal errors when uploading an image in WP media library.
(I had to fix the loading of the local stream wrapper to use the "new" namespaces first).

`"NOTICE: PHP message: PHP Warning:  opendir(/var/www/public/app/uploads/s3/img.utopia.org/uploads/2021/06/flower-1669899_1920*): failed to open dir: No such file or directory in /var/www/public/app/plugins/s3-uploads/inc/class-local-stream-wrapper.php on line 515"
"NOTICE: PHP message: PHP Warning:  scandir(s3://img.utopia.org/uploads/2021/06/flower-1669899_1920*): failed to open dir: &quot;\S3_Uploads\Local_Stream_Wrapper::dir_opendir&quot; call failed in /var/www/public/app/plugins/s3-uploads/inc/class-plugin.php on line 668"
"NOTICE: PHP message: PHP Warning:  scandir(): (errno 13): Permission denied in /var/www/public/app/plugins/s3-uploads/inc/class-plugin.php on line 668"
"NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: Return value of S3_Uploads\Plugin::get_files_for_unique_filename_file_list() must be of the type array, bool returned in /var/www/public/app/plugins/s3-uploads/inc/class-plugin.php:668"
"Stack trace:"
"#0 /var/www/public/wp/wp-includes/class-wp-hook.php(292): S3_Uploads\Plugin->get_files_for_unique_filename_file_list()"
"#1 /var/www/public/wp/wp-includes/plugin.php(212): WP_Hook->apply_filters()"
"#2 /var/www/public/wp/wp-includes/functions.php(2560): apply_filters()"
"#3 /var/www/public/wp/wp-admin/includes/file.php(908): wp_unique_filename()"
"#4 /var/www/public/wp/wp-admin/includes/file.php(1020): _wp_handle_upload()"
"#5 /var/www/public/wp/wp-admin/includes/media.php(303): wp_handle_upload()"
"#6 /var/www/public/wp/wp-admin/includes/ajax-actions.php(2549): media_handle_upload()"
"#7 /var/www/public/wp/wp-admin/async-upload.php(33): wp_ajax_upload_attachment()"
"#8 {main}"
"  thrown in /var/www/public/app/plugins/s3-uploads/inc/class-plugin.php on line 668"
`
I'll send in a pull request with my solution shortly.

Thanks in advance!

**Comment by VlasicVojislav** [comment]
Closing this as a duplicate.
