### ISSUE TITLE
Fatal error on plugin activation when manually installing

### ISSUE THREAD

**Issue by henrywright** [humanmade/S3-Uploads#538]
> PHP Fatal error:  Uncaught Error: Class 'S3_Uploads\Plugin' not found in wp-content/plugins/s3-uploads/inc/namespace.php:32

The steps I took were:

1. I downloaded the 3.0.2 manual-install.zip
2. I then visited Network Admin > Plugins
3. I then clicked "Add New"
4. I then clicked "Upload Plugin" and selected the zip from my computer
5. I then clicked "Install Now"
6. I then clicked "Network Activate"

**Comment by henrywright** [comment]
I did some digging and it seems a dependency requires PHP 7.2.5. The local install I used had PHP 7.0.33

**Comment by henrywright** [comment]
Note though the PHP version issue isn't related to this fatal error

**Comment by rmccue** [comment]
Hmm, this seems to indicate that the Composer autoloader hasn't been loaded correctly. Are you using manual-install while also using the AWS SDK elsewhere in your project?

**Comment by henrywright** [comment]
Hi @rmccue. Yes, I'm using the aws-ses-wp-mail plugin and I'm sure it uses the SDK

**Comment by henrywright** [comment]
@rmccue how would you use the manual install of aws-ses-wp-mail and s3-uploads together?

**Comment by djviruss** [comment]
Same Issue:
PHP Fatal error:  Uncaught Error: Class 'S3_Uploads\Plugin' not found in /var/www/html/wp-content/plugins/manual-install-1/inc/namespace.php:32
Stack trace:
#0 /var/www/html/wp-includes/class-wp-hook.php(303): S3_Uploads\init()
#1 /var/www/html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#2 /var/www/html/wp-includes/plugin.php(470): WP_Hook->do_action()
#3 /var/www/html/wp-settings.php(441): do_action()
#4 /var/www/html/wp-config.php(144): require_once('/var/www/html/w...')
#5 /var/www/html/wp-load.php(50): require_once('/var/www/html/w...')
#6 /var/www/html/wp-login.php(12): require('/var/www/html/w...')
#7 {main}
  thrown in /var/www/html/wp-content/plugins/manual-install-1/inc/namespace.php on line 32

**Comment by henrywright** [comment]
#377 may solve this issue
