### ISSUE TITLE
Uncaught Error Guzzle Promise promise_for()

### ISSUE THREAD

**Issue by CaldwellYSR** [humanmade/S3-Uploads#565]
I installed with manual install unzipping directly into my plugins directory. It has been working great until my latest wordpress update. Now I get the above error. When I look this one up it seems that `promise_for` is [deprecated](https://docs.aws.amazon.com/aws-sdk-php/v3/api/function-GuzzleHttp.Promise.promise_for.html). The full error log is

```
PHP Fatal error:  Uncaught Error: Call to undefined function GuzzleHttp\\Promise\\promise_for() in /var/www/html/wp-content/plugins/s3-uploads/vendor/aws/aws-sdk-php/src/S3/RegionalEndpoint/ConfigurationProvider.php:160
Stack trace:
#0 /var/www/html/wp-content/plugins/s3-uploads/vendor/guzzlehttp/promises/src/Promise.php(204): Aws\\S3\\RegionalEndpoint\\ConfigurationProvider::Aws\\S3\\RegionalEndpoint\\{closure}(Object(Aws\\S3\\RegionalEndpoint\\Exception\\ConfigurationException))
#1 /var/www/html/wp-content/plugins/s3-uploads/vendor/guzzlehttp/promises/src/Promise.php(169): GuzzleHttp\\Promise\\Promise::callHandler(2, Object(Aws\\S3\\RegionalEndpoint\\Exception\\ConfigurationException), NULL)
#2 /var/www/html/wp-content/plugins/s3-uploads/vendor/guzzlehttp/promises/src/RejectedPromise.php(42): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}(Object(Aws\\S3\\RegionalEndpoint\\Exception\\ConfigurationException))
#3 /var/www/html/wp-content/plugins/s3-uploads/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\\Promise\\RejectedPromise in /var/www/html/wp-content/plugins/s3-uploads/vendor/aws/aws-sdk-php/src/S3/RegionalEndpoint/ConfigurationProvider.php on line 160
```

**Comment by CaldwellYSR** [comment]
This turned out to be a plugin conflict with a different plugin using a newer version of Guzzle.
