### ISSUE TITLE
Where is "Aws\Common\Aws" ?

### ISSUE THREAD

**Issue by twmbx** [humanmade/S3-Uploads#95]
Have I done something wrong?
Just installed S3-Uploads & can't get verify or create-iam-user to work because of

```
Fatal error: Uncaught Error: Class 'Aws\Common\Aws' not found
```

When I checked the [aws sdk autoloader](https://github.com/humanmade/S3-Uploads/blob/master/lib/aws-sdk/aws-autoloader.php), I can't seem to find a mapping for "Aws\Common\Aws" ... Just me?

**Comment by spacedmonkey** [comment]
Interesting I am getitng this 

```
PHP Fatal error:  Class 'Aws\\Common\\Exception\\ServiceResponseException'
```

I wonder if it is related...

**Comment by twoSeats** [comment]
@spacedmonkey i would expect so, there are no "Aws\Common" mappings at all from what I could see.

**Comment by joehoyle** [comment]
@twoSeats can you make sure you are using the latest stable release from https://github.com/humanmade/S3-Uploads/releases thanks!

**Comment by twoSeats** [comment]
@joehoyle oh is that what it is? I'll give that a shot.

**Comment by seostudio** [comment]
Same problem. Newest version installed.

**Comment by simonhampel** [comment]
Just setting this up for the first time - pulled the latest version, tried to run create-iam-user and had this problem with Aws\Common\Aws missing:

```
$ wp s3-uploads create-iam-user --admin-key=XXX --admin-secret=YYY
PHP Fatal error:  Uncaught Error: Class 'Aws\Common\Aws' not found in /srv/www/example.com/wp-content/plugins/s3-uploads/inc/class-s3-uploads-wp-cli-command.php:155
Stack trace:
#0 [internal function]: S3_Uploads_WP_CLI_Command->create_iam_user(Array, Array)
#1 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(67): call_user_func(Array, Array, Array)
#2 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#3 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(351): call_user_func(Object(Closure), Array, Array)
#4 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(327): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#5 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(334): WP_CLI\Runner->run_command(Array, Array)
#6 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(757): WP_CLI\Runner->_run_command()
#7 phar:///usr/local/bin/wp/php/wp-cli.php(21): WP_CLI\Runner->start()
#8 phar:///usr/local/bin/wp/php/boot-phar.php(5): include('phar:///usr/loc...')
#9 / in /srv/www/example.com/wp-content/plugins/s3-uploads/inc/class-s3-uploads-wp-cli-command.php on line 155
Fatal error: Uncaught Error: Class 'Aws\Common\Aws' not found in /srv/www/example.com/wp-content/plugins/s3-uploads/inc/class-s3-uploads-wp-cli-command.php:155
Stack trace:
#0 [internal function]: S3_Uploads_WP_CLI_Command->create_iam_user(Array, Array)
#1 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/CommandFactory.php(67): call_user_func(Array, Array, Array)
#2 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#3 phar:///usr/local/bin/wp/php/WP_CLI/Dispatcher/Subcommand.php(351): call_user_func(Object(Closure), Array, Array)
#4 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(327): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#5 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(334): WP_CLI\Runner->run_command(Array, Array)
#6 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(757): WP_CLI\Runner->_run_command()
#7 phar:///usr/local/bin/wp/php/wp-cli.php(21): WP_CLI\Runner->start()
#8 phar:///usr/local/bin/wp/php/boot-phar.php(5): include('phar:///usr/loc...')
#9 / in /srv/www/example.com/wp-content/plugins/s3-uploads/inc/class-s3-uploads-wp-cli-command.php on line 155
```

**Comment by uliporeggia** [comment]
Same issue as @simonhampel

**Comment by joehoyle** [comment]
I think this problem is coming from another copy of the AWS SDK being loaded which is a different version, could anyone confirm if they are using another aws sdk elsewhere in their codebase? Thanks!

**Comment by puckbag** [comment]
`Aws\Common` is old and does not exist in AWS-PHP-SDK v3 which is included in the current S3-Uploads v2 (beta).

#133 resolves this issue for me.

**Comment by andrewodri** [comment]
I just installed this plugin for the first time, and I am getting the error mentioned above. As @puckbag mentioned, it seems that the old SDK references are still present in the v2.0.0 release:

https://github.com/humanmade/S3-Uploads/blob/70d50a23b2665a02abd410647c887306decfe940/inc/class-s3-uploads-wp-cli-command.php#L159-L164

**Comment by dingo-d** [comment]
From what I've plucked on the v3 of the sdk, the iam instance should be created using

`Aws\Iam\IamClient`

class.

Something like

```php
$iam = new \Aws\Iam\IamClient( [
    'profile' => 'default',
    'region' => S3_UPLOADS_REGION,
    'version' => 'latest',
] );
````
The rest of the methods are the same.

https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-iam-2010-05-08.html

This assumes that the plugin is installed using composer, and that lib `Aws` is not used, but the one from `vendors` is used.

**Comment by ming371** [comment]
I'm quite new to this, but I found that the solution by @dingo-d worked for me with some modification.  I replaced this line:
```
$iam = Aws\Common\Aws::factory( array( 'key' => $args_assoc['admin-key'], 'secret' => $args_assoc['admin-secret'] ) )->get( 'iam' );
```
with this code:
```
$iam = new Aws\Iam\IamClient([
    'version' => 'latest',
    'region'  => S3_UPLOADS_REGION,
    'credentials' => [
        'secret' => $args_assoc['admin-secret'],
	'key' => $args_assoc['admin-key'],
    ],
]);
```

**Comment by dingo-d** [comment]
Yeah, this should work if you are not using `S3_UPLOADS_USE_INSTANCE_PROFILE ` :+1:

**Comment by pixelbrad** [comment]
Ran into this issue just now on a fresh setup of v2.2.1 (latest stable at the time of writing).
